import sys
import hashlib 

# hashing script 
def detect_hash(hash_value):
    hash_algorithms = {
        "MD5": hashlib.md5,
        "SHA-1": hashlib.sha1,
        "SHA-256": hashlib.sha256,
        "SHA-512": hashlib.sha512
    }

    for algo_name, algo_func in hash_algorithms.items(): 
        test_value = "example"
        test_hash = algo_func(test_value.encode()).hexidigest()

        if len(hash_value) == len(test_hash):
            return f"The hash seems to be generated by {algo_name}"

    return "Type of hash not recognized."

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Error: field requires a hash.")
        sys.exit(1)
    
    hash_input = sys.argv[1].strip()
    result = detect_hash(hash_input)
    print(result)